--INSERTIONS
--FoodEstablishment
--stores with no name will take on the name of their contact person
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person) value ("0001","Albao's Store","Kiosk","Roxas Ave Corner Roces St., Diliman, Quezon City, Metro Manila","5:30am - 11:00pm","Monday-Sunday",null,null);
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person) value ("0002","Smokey's Store", "Kiosk","Roxas Ave Corner Roces St., Diliman, Quezon City, Metro Manila","6:00am-9:00pm", "Tuesday-Sunday","09178580281","Perla Buduan");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person) value ("0003","Floriza's Store","Kiosk","Roxas Ave Corner Roces St., Diliman, Quezon City, Metro Manila",null,"Monday-Sunday",null,"Floriza 'Nene' Badion");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person) value ("0004","Janine's Store","Kiosk","Roxas Ave Corner Roces St., Diliman, Quezon City, Metro Manila","7:00am-9:00pm","Monday-Sunday",null,null);
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person) value ("0005",'Isabel Bakes "Cookies from Home"',"Kiosk","Roxas Ave Corner Roces St., Diliman, Quezon City, Metro Manila","7:00am-7:00pm","Monday-Saturday","09294061301","Analyn Manarang");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person) value ("0006", "Famous Belgian Waffles","Kiosk","Roxas Ave Corner Roces St., Diliman, Quezon City, Metro Manila","7:00am-7:00pm","Monday-Saturday","09294061301","Analyn Manarang");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person,free_water,bring_your_own_baon_incentive,clean_as_you_go,seating_capacity) value ("0007","Vargas Museum Cafe","Cafe","Vargas Museum, Roxas Ave, Diliman, Quezon City, Metro Manila","9:00am-6:00pm","Tuesday-Friday","09756000017","Elvie Fernandez","Yes","No","Yes",60);
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person,additional_cost_for_takeOut,seating_capacity) value ("0008","Narry's Kiosk","Kiosk","UP Main Library, Diliman,Quezon City 1100,Metro Manila, Diliman, Quezon City, Metro Manila","7:00am-9:00pm","Monday-Sunday","09665427495","Narry","4.00",12);
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person,seating_capacity) value ("0009","Chicksrule","Kiosk","UP Main Library, Diliman,Quezon City 1100,Metro Manila, Diliman, Quezon City, Metro Manila","7:00am-7:00pm","Tuesday-Friday","09260923543","Jennylyn",8);
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person) value ("0010","Tita Carm's Budget Meals","Kiosk","UP Main Library, Diliman,Quezon City 1100,Metro Manila, Diliman, Quezon City, Metro Manila","7:00am-7:00pm","Monday-Friday","09777841231","Tita Carm's");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person) value ("0011","Diliman's Brew","Kiosk","UP Main Library, Diliman,Quezon City 1100,Metro Manila, Diliman, Quezon City, Metro Manila","7:00am-9:00pm","Monday-Sunday",null,null);
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person) value ("0012","Potato Corner","Kiosk","UP Main Library, Diliman,Quezon City 1100,Metro Manila, Diliman, Quezon City, Metro Manila","9:00am-6:30pm","Monday-Sunday",null,null);
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person,description) value ("0013","King's Crispy Liempo","Stall","Zoology Building, Quirino Avenue, Diliman, Diliman, Quezon City, 1101 Metro Manila","8:10am-5:00pm","Monday-Friday",null,null,"Stalls in new CASAA take turns in being open during Saturdays. However, there is always at least 2 stalls open during a Saturday.");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person,description) value ("0014","The Galley","Stall","Zoology Building, Quirino Avenue, Diliman, Diliman, Quezon City, 1101 Metro Manila","7:00am-5:00pm","Monday-Friday","09169816934","Lea Mergal","Stalls in new CASAA take turns in being open during Saturdays. However, there is always at least 2 stalls open during a Saturday.");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person,description) value ("0015","Gloria's","Stall","Zoology Building, Quirino Avenue, Diliman, Diliman, Quezon City, 1101 Metro Manila","7:00am-5:00pm","Monday-Friday","Stalls in new CASAA take turns in being open during Saturdays. However, there is always at least 2 stalls open during a Saturday.");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person,description) value ("0016","IMAS","Stall","Zoology Building, Quirino Avenue, Diliman, Diliman, Quezon City, 1101 Metro Manila","8:00am-5:30pm","Monday-Friday","09676073555","Nel","Stalls in new CASAA take turns in being open during Saturdays. However, there is always at least 2 stalls open during a Saturday.");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person,description) value ("0017","Phily's (Beef Peppershop)","Stall","Zoology Building, Quirino Avenue, Diliman, Diliman, Quezon City, 1101 Metro Manila","8:30am-5:00pm","Monday-Friday","09752688570","Grace Garcia","Stalls in new CASAA take turns in being open during Saturdays. However, there is always at least 2 stalls open during a Saturday.");
insert into FoodEstablishment (fe_ID,name,type,location,open_hours,open_days,contact_number,contact_person,additional_cost_for_takeOut,free_water,seating_capacity,clean_as_you_go) value ("0018","Erlinda's Service","Cafeteria","T.H. Pardo de Tavera Street, Diliman, Quezon City, Metro Manila","6:30am-5:00pm","Monday-Friday","9258246","Ate Cheng","P5.00 (Small Box) / P7.00 (Large Box)","Yes",100,"Yes");
